"""
Main ingestion service logic - handles file transfer and JSON updates
"""
"""
This is the main ingestion servic which does the following task:-
1. Take file from the Nameparase Json file from the S3 and upload its input and output uri 
2. Take the input file from the MINIO and then upload it to the S3 and gets its input and output uri 
3. Now After this we have to make the updation in the workflow.
"""
from asyncio import tasks
import os
import uuid
from datetime import datetime
from typing import Dict, Any, Optional
from s3_utils import S3Manager
from minio_utils import MinIOManager
from config import Config


class IngestionService:
    """Main service class for handling ingestion workflow"""
    
    def __init__(self):
        self.s3_manager = S3Manager()
        self.minio_manager = MinIOManager()
    
    def generate_run_id(self, prefix: Optional[str] = None) -> str:
        """
        Generate unique run ID
        
        Args:
            prefix: Optional prefix for run ID
            
        Returns:
            Unique run ID (e.g., "run-20251112-abc123")
        """

        """Nothing much just returns the runid"""
        timestamp = datetime.now().strftime("%Y%m%d-%H%M%S")
        unique_id = str(uuid.uuid4())[:8]
        
        if prefix:
            return f"{prefix}-{timestamp}-{unique_id}"
        return f"run-{timestamp}-{unique_id}"
    

    def ingest_file_and_update_json(
        self,
        minio_input_uri: str,
        source_json_s3_key: str,
        run_id: Optional[str] = None,
        workflow_id: Optional[str] = None
    ) -> Dict[str, Any]:

        """
        Main ingestion function:
        1. Download file from MinIO
        2. Upload to S3
        3. Fetch JSON from S3 (e.g., 1000861509.WBNameParse.json)
        4. Update input/output URIs
        5. Re-upload updated JSON to S3
        
        Args:
            minio_input_uri: MinIO URI of input file (e.g., "minio://bucket/path/file.csv")
            source_json_s3_key: S3 key of source JSON (e.g., "conductor-poc/1000861509.WBNameParse.json")
            run_id: Optional run ID (auto-generated if not provided)
            workflow_id: Optional workflow ID for metadata
            
        Returns:
            Dictionary with run_id, S3 URIs, and updated JSON location
        """


        """
        This is the main function takes the downloaded file from MNIO then we are going to upload it on S3 and take its input and output uri 
        after this we will fetch json from s3 and then update its input and output URIs
        and then we will Re-upload json to s3.
   
        """
        # Generate run ID if not provided
        if not run_id:
            run_id = self.generate_run_id()
        
        # Create S3 paths for this run
        """ Here we are going to create the input key and output key according to the run id that will be generated by timestamp and it will the unique run id  """
        input_filename = os.path.basename(minio_input_uri)
        s3_input_key = f"{Config.S3_PREFIX}/runs/{run_id}/input/{input_filename}"
        #The output file name will be the same just we have to replace its prefix from in to out
        s3_output_key = f"{Config.S3_PREFIX}/runs/{run_id}/output/{input_filename.replace('.in', '.out')}"
        
        # Generate report URI (similar to 1000861509.counts.txt structure)
        # Extract base name from source JSON (e.g., "1000861509" from "1000861509.WBNameParse.json")
        json_basename = os.path.basename(source_json_s3_key)  
        report_base = json_basename.split('.')[0] if '.' in json_basename else run_id
        s3_report_key = f"{Config.S3_PREFIX}/runs/{run_id}/report/{report_base}.counts.txt"
        
        s3_json_key = f"{Config.S3_PREFIX}/runs/{run_id}/{json_basename}"
        
        # Step 1: Download file from MinIO to local temp
        local_temp_dir = os.path.join(Config.LOCAL_TEMP_DIR, run_id)
        os.makedirs(local_temp_dir, exist_ok=True)
        local_file_path = os.path.join(local_temp_dir, input_filename)
        

        """Here we are downloading it from MINIO"""
        print(f"Downloading from MinIO: {minio_input_uri}")
        self.minio_manager.download_file(minio_input_uri, local_file_path)
        
        # Step 2: Upload file to S3
        """Then We are going to upload it on S3"""
        """Also will be going to take the input and output uri"""
        print(f"Uploading to S3: s3://{Config.S3_BUCKET}/{s3_input_key}")
        s3_input_uri = self.s3_manager.upload_file(local_file_path, s3_input_key)
        # Step 3: Fetch JSON from S3, update URIs, and re-upload
        print(f"Fetching JSON from S3: {source_json_s3_key}")
        s3_output_uri = f"s3://{Config.S3_BUCKET}/{s3_output_key}"
        s3_report_uri = f"s3://{Config.S3_BUCKET}/{s3_report_key}"
        
        """Then will be going to update the JSON File """
        updated_json_uri = self.s3_manager.fetch_and_update_json(
            source_s3_key=source_json_s3_key,
            input_uri=s3_input_uri,
            output_uri=s3_output_uri,
            target_s3_key=s3_json_key,
            report_uri=s3_report_uri,
            workflow_id=workflow_id
        )
        
        #Then we will remove the local temp file 
        # Clean up local temp file
        try:
            os.remove(local_file_path)
            os.rmdir(local_temp_dir)
        except Exception as e:
            print(f"Warning: Could not clean up temp files: {e}")
        
        return {
            "run_id": run_id,
            "s3_input_uri": s3_input_uri,
            "s3_output_uri": s3_output_uri,
            "s3_report_uri": s3_report_uri,
            "updated_json_uri": updated_json_uri,
            "updated_json_s3_key": s3_json_key
        }
    


    #This is the Execute Service Chain that chains the multiple services and update the input and output uris based on workflow that is defined 
    def execute_service_chain(self,workflow_json:dict,minio_input_uri:str,workflow_id: Optional[str] = None):
        """
        Execute the services direclty based on the workflow task
        """
        service_results={}
        current_input_uri=minio_input_uri
        #Extract task with the kafka_request(assumed service task)
        service_tasks=[
            task for task in workflow_json.get("tasks",[])
            if "kafka_request" in task.get("inputParameters",{})
        ]

        for task in service_tasks:
            service_name=task.get("name") or task.get("taskReferenceName")
            source_json_s3_key=f"conductor-poc/{service_name}.json"

            print(f"\nExecuting service: {service_name}")
            result=self.ingest_file_and_update_json(
                minio_input_uri=current_input_uri,
                source_json_s3_key=source_json_s3_key,
                workflow_id=workflow_id
            )

            #Pass output of this service as the input to the next service.
            current_input_uri=result["s3_output_uri"]
            service_results[service_name]=result
    
        return service_results

    
    def update_workflow_template(
        self,
        workflow_json: dict,
        service_results: Dict[str, Dict[str, Any]]
    ) -> dict:
        """
        Update workflow tasks with metadata URLs pointing to updated service JSONs
        """
        for task in workflow_json.get("tasks", []):
            task_name = task.get("name") or task.get("taskReferenceName")
            if task_name in service_results:
                metadata_url = service_results[task_name]["updated_json_uri"]
                task.setdefault("inputParameters", {}).setdefault("kafka_request", {})["metadataUrl"] = metadata_url
                print(f"Updated task '{task_name}' with metadata URL: {metadata_url}")

        return workflow_json



if __name__=="__main__":
    service=IngestionService() 
    #minioinput_uri
    #source_json_s3_key
    #runid
    #workflowid
    #For runnign the ingest_file and update json
    output=service.ingest_file_and_update_json("minio://raw-data/1000861642.in","conductor-poc/1000861509.WBNameParse.json","test-run-123","workflow-test-123")

    for key,value in output.items():
        print(f"{key}->{value}")
        print()
